version: '3.9'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - OTP_SECRET_ENCRYPTION_PASSWORD=${OTP_SECRET_ENCRYPTION_PASSWORD}
    entrypoint: ["/app/entrypoint.sh"]
    expose:
      - "5000"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl

volumes:
  instance: